SELECT DELIVERERID, SUM(AMOUNT)
FROM PENALTIES
WHERE DELIVERERID IN (SELECT DELIVERERID
                      FROM DELIVERERS
                      WHERE TOWN = 'Inglewood')
GROUP BY DELIVERERID
HAVING COUNT(*) >= 2;