SELECT DISTINCT NAME, INITIALS
FROM DELIVERERS D, COMPANIES C, PENALTIES P
WHERE D.DELIVERERID = C.DELIVERERID AND C.DELIVERERID = P.DELIVERERID AND DATA > TO_DATE('31/12/1980', 'DD/MM/YYYY')
ORDER BY NAME;