SELECT DISTINCT D.DELIVERERID
FROM DELIVERERS D, COMPANIES C, COMPANYDEL CD
WHERE CD.DELIVERERID = D.DELIVERERID AND CD.COMPANYID = C.COMPANYID
    AND YEAR_OF_BIRTH > 1962 AND MANDATE = 'first'
ORDER BY D.DELIVERERID DESC;