SELECT DISTINCT NAME
FROM DELIVERERS D
WHERE (D.TOWN = 'Inglewood' OR D.TOWN = 'Stratford') AND D.DELIVERERID IN
    (SELECT COMPANYDEL.DELIVERERID
    FROM COMPANYDEL
    GROUP BY COMPANYDEL.DELIVERERID
    HAVING COUNT(*) >= 2);