SELECT C1.DELIVERERID
FROM COMPANYDEL C1, COMPANYDEL C2
WHERE C1.DELIVERERID <> 57 and C2.DELIVERERID = 57 and C1.COMPANYID = C2.COMPANYID and C1.DELIVERERID NOT IN (SELECT DELIVERERID FROM COMPANYDEL C3 WHERE C3.COMPANYID <> C2.COMPANYID);