SELECT D.DELIVERERID 
FROM DELIVERERS D, COMPANYDEL C
WHERE D.DELIVERERID = C.DELIVERERID
GROUP BY D.DELIVERERID
HAVING COUNT(DISTINCT C.COMPANYID) = (SELECT COUNT(DISTINCT COMPANYID) FROM COMPANYDEL);